### ISSUE TITLE
Missing ID-check when looking for log-channels

### ISSUE THREAD

**Issue by ogrady** [ogrady/Botgart#74]
```
2020-07-19T23:08:44.295Z info [Reauthenticate.js]: Unauthing Foobar.
2020-07-19T23:08:44.343Z error [DB.js]: DB execute: Cannot read property 'id' of undefined (stack: Error
    at Database.execute (/user/Botgart/built/DB.js:89:74)
    at LogChannelRepository.execute (/user/Botgart/built/repositories/AbstractDbRepository.js:8:24)
    at LogChannelRepository.getLogChannels (/user/Botgart/built/repositories/LogChannelRepository.js:6:21)
    at BotgartClient.discordLog (/user/Botgart/built/BotgartClient.js:198:52)
    at Reauthenticate.<anonymous> (/user/Botgart/built/commands/Reauthenticate.js:81:36)
    at Generator.next (<anonymous>)
    at fulfilled (/user/Botgart/built/commands/Reauthenticate.js:5:58))
```

This is probably the reason why unauth-messages are not forwarded to Discord anymore and therefore related to https://github.com/ogrady/Botgart/issues/71.

**Comment by ogrady** [comment]
Fixed in https://github.com/ogrady/Botgart/commit/9ae2df5c707404848edada81ec08bcae3840668a
